# Generated by Django 4.2.5 on 2023-10-17 18:25

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(verbose_name='Количество продукта в наличии')),
                ('data', models.DateTimeField(verbose_name='Дата и время')),
                ('title', models.CharField(max_length=100, verbose_name='Каталог')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('freeDelivery', models.BooleanField(default=True, verbose_name='Бесплатная доставка')),
                ('images', models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_directory_path, verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.review', verbose_name='Отзывы')),
                ('specifications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.specifications', verbose_name='Характеристики продукта')),
                ('tags', models.ManyToManyField(to='catalog.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
