# Generated by Django 4.2.5 on 2023-11-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_product_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="review",
        ),
        migrations.RemoveField(
            model_name="product",
            name="specification",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="specifications",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specifications",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="product",
            field=models.ManyToManyField(
                related_name="tags", to="catalog.product", verbose_name="Продукт"
            ),
        ),
    ]
